version: '3.0'
services:
  db:
    image: mongo
    container_name: 'db'
    ports:
      - 27017:27017
    volumes:
    - /mongodb:/data/db
    
  host:
    container_name: "host"
    ports:
        - 80:80
        - 443:443
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Prod